flask:
    build: .
    command: 'python manage.py runserver --host 0.0.0.0'
    ports:
      - '5000:5000'
    expose:
      - '5000'
    links:
      - redis
      - celery

celery:
    build: .
    command: 'celery worker -A celery_worker.celery --loglevel=info'
    links:
      - redis

redis:
    image: redis
    expose:
      - '6379'
    ports:
      - '6379:6379'
