rabbit:
  image: rabbitmq:3-management
  hostname: "my-rabbit"
  env_file:
    - .env
  # environment:
  #   RABBITMQ_DEFAULT_USER: "user"
  #   RABBITMQ_DEFAULT_PASS: "password"
  ports:
    - "15672:15672"
    - "8080:5672"
  labels:
    NAME: "rabbit-server"
