FROM python:2.7-slim
# FROM ubuntu:14.04

# # Update
# RUN apt-get update
# RUN apt-get install -y python
# RUN apt-get install -y python-pip
#
# # Install app dependencies
# RUN pip install --upgrade pip

WORKDIR /app
COPY . /app

RUN pip install -r requirements.txt

EXPOSE 5000

# CMD python run.py
CMD python manage.py runserver -h 0.0.0.0 -p 5000
