rabbit:
  image: rabbitmq:3-management
  hostname: "my-rabbit"
  environment:
    RABBITMQ_DEFAULT_USER: "user"
    RABBITMQ_DEFAULT_PASS: "password"
  ports:
    - "15672:15672"
    - "8080:5672"
  labels:
    NAME: "rabbit-server"

# services:
#   rabbit:
#     image: "rabbitmq:3-management"
#     hostname: "rabbit-server"
#     environment:
#     RABBITMQ_DEFAULT_VHOST: "/"
#     ports:
#       - "15672:15672"
#       - "5672:5672"
#     labels:
#       NAME: "rabbit-server"

# app:
#   build: .
#   dockerfile: Dockerfile
#   links:
#     - redis
#   ports:
#     - "5000:5000"
# redis:
#   image: redis
#   ports:
#     - "6379:6379"
#   expose:
#     - "6379"
