flask:
    build: .
    command: "python manage.py runserver"
    ports:
        - '5000:5000'
    links:
        - redis
        - celery

celery:
    build: .
    command: "celery worker -A celery_worker.celery --loglevel=info"
    links:
        - redis
    
redis:
    image: redis
    ports:
        - '6379:6379'
